mode: eval  # Options: train, eval, render

game: Pong
seed: 0
environments: 8  # Number of environments used for training
times: 10  # Number of episodes for evaluation (only applicable in eval mode)

reward: human  # Options: env, human, mixed (optional)
prune: default  # Options: default, external (optional)

rgb: false  # Use RGB observation space (optional)
hud: false  # Use HUD objects (optional)
hackatari: false  # Use Hackatari as environment (optional)
mods: ""  # List of mods to use with Hackatari, separated by commas (optional)

progress: true  # Display progress bar during training (optional)
record: false  # Whether to record rendered video (only applicable in render mode)
viper: false  # Evaluate the extracted viper tree instead of a checkpoint (only for render mode)
exclude_properties: false  # Exclude properties from feature vector (optional)
nb_frames: 0  # Stop recording after a certain number of frames (only for render mode)
print_reward: false  # Display the reward in the console (only for render mode)
